# Generated by Django 4.2.2 on 2023-06-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_phone_type',
            field=models.BooleanField(default=False),
        ),
    ]
